#! /bin/sh

feh --bg-fill /usr/share/backgrounds/view.jpg
.config/lemonbar/lemonbarrc &
compton --config .config/compton.conf &

bspc config border_width 0
bspc config window_gap 20
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

bspc monitor HDMI3 -d I II
bspc monitor HDMI2 -d III IV

bspc rule -a Chromium desktop='^1'

chromium &
urxvt &

